/****************
 * COM EtherCAT
 ****************/

#pragma once

#include <xs1.h>
#include <platform.h>

/* TODO Make moduel_ethercat use these port declarations
on tile[0]: out port ecatRST = XS1_PORT_1F;
on tile[0]: in  port ecatIRQ = XS1_PORT_1I;
on tile[0]: in  port ecatBUSY = XS1_PORT_1J;
on tile[0]: out port ecatWR = XS1_PORT_1K;
on tile[0]: out port ecatRD = XS1_PORT_1L;
on tile[0]: out port ecatCS = XS1_PORT_1M;
on tile[0]:     port ecatData = XS1_PORT_16A;
on tile[0]: out port ecatAddress = XS1_PORT_16B;
*/


